# Generated by Django 6.0.5 on 2026-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.URLField(
                        default="https://bizimages.withfloats.com/actual/3f6bfde19dbe4c178ea34e0e0ae96ad7.jpg"
                    ),
                ),
                ("cuisine", models.CharField(max_length=200)),
                ("rating", models.FloatField()),
            ],
        ),
    ]
