# Generated by Django 6.0.7 on 2026-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_remove_customer_password_customer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(related_name="carts", to="delivery.item"),
        ),
    ]
