# Generated by Django 6.0.7 on 2026-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_alter_cart_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="item",
            name="picture",
            field=models.URLField(
                default="https://www.indiafilings.com/learn/wp-content/uploads/2024/08/How-to-Start-Food-Business.jpg",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="picture",
            field=models.URLField(
                default="https://bizimages.withfloats.com/actual/3f6bfde19dbe4c178ea34e0e0ae96ad7.jpg",
                max_length=500,
            ),
        ),
    ]
